WITH FIRSTGEN AS (
    SELECT *
    FROM  ECOLI_DATA
    WHERE PARENT_ID IS NULL), 
    SECONDGEN AS (
    SELECT E.ID, E.PARENT_ID
    FROM ECOLI_DATA E
    JOIN FIRSTGEN F ON E.PARENT_ID = F.ID),
    THIRDGEN AS (
    SELECT E.ID, E.PARENT_ID
    FROM ECOLI_DATA E
    JOIN SECONDGEN S ON E.PARENT_ID = S.ID)
SELECT ID
FROM THIRDGEN
ORDER BY ID ASC;