-- 재귀함수
-- 첫번째 세대를 찾고, 세대가 더이상 없을때까지 다음 세대를 찾아야 한다
WITH RECURSIVE CTE AS ( -- RECURSIVE : 재귀 함수
    -- ANCHOR : 1세대 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION -- 현재 세대를 숫자로 표현
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL -- 위의 1세대의 결과와, 아래 계산된 세대에 행별합을 진행한다
    
    SELECT E.ID, E.PARENT_ID, C.GENERATION+1 -- 1세대 증가
    FROM ECOLI_DATA E
    JOIN CTE C ON E.PARENT_ID = C.ID
)
SELECT COUNT(*) AS COUNT, PARENT.GENERATION
FROM CTE PARENT
LEFT JOIN ECOLI_DATA CHILD ON PARENT.ID = CHILD.PARENT_ID -- 만약 부모에게 자식이 있다면, 자식의 부모 항목엔 부모가 들어있을 것
WHERE CHILD.ID IS NULL
GROUP BY PARENT.GENERATION
ORDER BY PARENT.GENERATION;