SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENT
JOIN ECOLI_DATA CHILD ON PARENT.ID = CHILD.PARENT_ID
WHERE (CHILD.GENOTYPE | PARENT.GENOTYPE) = CHILD.GENOTYPE
ORDER BY ID ASC;